package com.example.foodtracker.ui.screen

val QUOTES = listOf(
    "Take care of your body — it’s the only place you have to live.",
    "Small steps every day lead to big results.",
    "Your health is an investment, not an expense.",
    "One healthy meal won’t make you fit, just like one unhealthy meal won’t make you unhealthy — it's about consistency.",
    "Fall in love with taking care of yourself.",
    "Healthy habits are built one choice at a time.",
    "Discipline is choosing what you want most over what you want now.",
    "Your body hears everything your mind says — stay positive.",
    "Every step counts — keep moving.",
    "Health is the greatest wealth.",
    "Your future self is counting on you — don't let them down.",
    "A little progress each day adds up to big changes.",
    "Commit to be fit.",
    "When you feel like quitting, remember why you started.",
    "If it doesn’t challenge you, it won’t change you.",
    "Stronger than yesterday.",
    "Be patient — nothing worth having comes overnight.",
    "Sweat now, shine later.",
    "The greatest project you'll ever work on is you.",
    "Success starts with self-discipline.",
    "Eat better, feel better.",
    "Your diet is a bank account — good food choices are good investments.",
    "You are what you eat — choose wisely.",
    "Nourish to flourish.",
    "Healthy eating is a form of self-respect.",
    "Eat for the body you want, not for the body you have.",
    "Food is fuel — choose premium.",
    "If you keep good food in your fridge, you will eat good food.",
    "A healthy diet is a solution to many of our health-care problems.",
    "Don’t dig your grave with your own knife and fork.",
    "Eat food that loves you back.",
    "Health starts in the kitchen.",
    "Real food doesn’t have ingredients — real food is ingredients.",
    "A healthy outside starts from the inside.",
    "What you eat in private, you wear in public.",
    "Your body becomes what you feed it.",
    "Let food be thy medicine.",
    "Don’t count calories — make calories count.",
    "Cravings don’t last — discipline does.",
    "Eat less sugar — you are sweet enough already.",
    "Take care of your mind — it runs your body.",
    "Progress, not perfection.",
    "Self-care isn’t selfish — it’s essential.",
    "Consistency builds confidence and strength.",
    "Don’t wish for it — work for it.",
    "Believe you can, and you're halfway there.",
    "Be stronger than your excuses.",
    "Motivation gets you started — habit keeps you going.",
    "Every healthy choice is a celebration of life.",
    "Don’t stop until you’re proud.",
    "Your habits define you — choose wisely.",
    "The only bad workout is the one you didn’t do.",
    "Feed your body good food and your soul good thoughts.",
    "Wellness is the new wealth.",
    "When you feel tired, learn to rest — not quit.",
    "Focus on health, not weight.",
    "Health isn’t about being perfect — it’s about effort.",
    "You don’t have to go fast — you just have to start.",
    "Make your body your best friend, not your enemy.",
    "Change your habits, change your life.",
    "Balance is the key to everything.",
    "Move your body daily — energy creates energy.",
    "A calm mind brings inner strength.",
    "Happiness is the highest form of health.",
    "Take time to care for your body and soul.",
    "Rest and recovery are part of the process.",
    "Health requires healthy thoughts too.",
    "A healthy lifestyle is a journey, not a destination.",
    "Fitness is not a punishment — it’s a blessing.",
    "Drink water, move daily, sleep deeply, stay grateful.",
    "Keep going.",
    "Eat clean. Train mean. Live lean.",
    "Body under construction — mind on a mission.",
    "Fuel your body. Feed your soul.",
    "Do it for your health.",
    "Sweat, smile, repeat.",
    "Health first, everything else later.",
    "You got this!",
    "Start today, not tomorrow.",
    "Stay healthy, stay happy.",
    "Healthy choices, every day.",
    "Consistency beats perfection.",
    "Move more, eat better, stress less.",
    "You become what you repeatedly do.",
    "Choose health every single moment.",
    "Nothing tastes as good as being healthy feels.",
    "Good habits are hard to build — bad habits are hard to break.",
    "Your daily routine determines your future.",
    "Slow progress is still progress.",
    "Success is built on daily discipline.",
    "Love yourself enough to live a healthy life.",
    "Be kind to your body — it's doing its best for you.",
    "Enjoy the process, honor the journey.",
    "You deserve to live a healthy life.",
    "Treat your body like you care — because you do.",
    "The goal isn’t to be perfect, just better than yesterday.",
    "Let your choices reflect your dreams, not your fears.",
    "Choose what helps your heart bloom.",
    "Live well — feel well — be well.",
    "You are your longest commitment — take care of yourself."
)
